CC = gcc
CFLAGS = -Wall -g

all: Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8

Q1: Q1.c
	$(CC) $(CFLAGS) -o Q1 Q1.c

Q2: Q2.c
	$(CC) $(CFLAGS) -o Q2 Q2.c

Q3: Q3.c
	$(CC) $(CFLAGS) -o Q3 Q3.c

Q4: Q4.c
	$(CC) $(CFLAGS) -o Q4 Q4.c

Q5: Q5.c
	$(CC) $(CFLAGS) -o Q5 Q5.c

Q6: Q6.c
	$(CC) $(CFLAGS) -o Q6 Q6.c

Q7: Q7.c
	$(CC) $(CFLAGS) -o Q7 Q7.c

Q8: Q8.c
	$(CC) $(CFLAGS) -o Q8 Q8.c

clean:
	rm -f Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8
